language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools
    - platform-tools
    
    # Build tools version
    - build-tools-28.0.3

    # SDK version
    - android-28

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # System images
    - sys-img-x86-android-26
    - sys-img-armeabi-v7a-android-22
